# Generated by Django 2.2.10 on 2020-12-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20201228_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='url',
            field=models.URLField(verbose_name='活动链接'),
        ),
    ]
